"""Evidence chains: why a finding exists, step by step, with proof.

Every finding already carries its rationale, frames and a Wireshark filter.
This module assembles them into the chain an analyst (or a judge) actually
walks when deciding whether to trust a conclusion:

    observed facts  ->  rule applied  ->  verdict + confidence
          |                                    |
    exact frames / protocol lines        what the ML layer adds (context only)
          |                                    |
    evidence quality limits              posture impact and blast radius

Nothing here is generated by a language model. Each step is traced to a stored
fact — a parsed protocol line, a policy rule, a score term — so the chain can
be reproduced from the capture by someone who does not trust the tool.
"""

from __future__ import annotations

from app.detection.engine import load_policy
from app.models.capture import Capture
from app.models.finding import Finding
from app.models.session import EmailSession
from app.posture.scoring import _DIMENSION_CATEGORIES, _SEVERITY_CEILING

_EVIDENCE_LABELS = {
    "observed_token": "Capability token observed on the wire",
    "expected_token": "Token a legitimate server sends",
    "baseline_scope": "Baseline used for comparison",
    "baseline_established": "Baseline established",
    "encryption_state": "Terminal encryption state",
    "tls_version": "Negotiated TLS version",
    "cipher_suite": "Negotiated cipher suite",
    "clients_offering_pqc": "Clients offering hybrid PQC",
    "tls_sessions": "TLS sessions observed",
    "domain": "Mail domain",
    "has_gaps": "Stream has missing bytes",
    "session_complete": "Session termination observed",
}

_DIMENSION_LABELS = {
    "transport": "Transport Security",
    "tls_version": "TLS Configuration",
    "crypto": "Cryptographic Strength",
    "pfs": "Forward Secrecy",
    "behaviour": "Behavioural Consistency",
}


def _label(key: str) -> str:
    return _EVIDENCE_LABELS.get(key, key.replace("_", " ").capitalize())


def _facts(evidence: dict) -> list[dict]:
    """Flatten the evidence dict into labelled facts; nested dicts are kept whole."""
    facts = []
    for key, value in (evidence or {}).items():
        if value in (None, [], {}):
            continue
        facts.append({"key": key, "label": _label(key), "value": value})
    return facts


def explain(
    capture: Capture,
    finding: Finding,
    session: EmailSession | None,
    blast_radius: dict | None = None,
) -> dict:
    rule = load_policy()["rules"].get(finding.category, {})
    frames = set(finding.evidence_frames or [])

    # --- Observations: the protocol lines at the cited frames -----------------
    observations = []
    if session is not None:
        for event in session.events or []:
            if event.get("frame") in frames:
                observations.append({
                    "frame": event.get("frame"),
                    "direction": event.get("direction"),
                    "kind": event.get("kind"),
                    "detail": event.get("detail"),
                })
        if not observations:
            # The finding cites the session as a whole; show its defining steps.
            observations = [
                {"frame": t.get("frame"), "direction": None, "kind": "state_transition",
                 "detail": f"{t.get('from')} → {t.get('to')} ({t.get('trigger')})"}
                for t in (session.state_transitions or [])
            ]

    # --- Reasoning chain -------------------------------------------------------
    steps = []
    if observations:
        first = observations[0]
        steps.append({
            "kind": "observation",
            "title": "What the capture shows",
            "text": (
                f"{len(observations)} protocol event(s) cited, starting at frame "
                f"{first['frame']}: {first['detail'] or first['kind']}."
            ),
        })
    elif finding.evidence:
        steps.append({
            "kind": "observation",
            "title": "What the capture shows",
            "text": finding.description,
        })

    thresholds = {
        k: v for k, v in rule.items()
        if k not in ("severity", "confidence", "title", "recommendation", "standards")
    }
    steps.append({
        "kind": "rule",
        "title": f"Rule applied: {finding.category}",
        "text": (
            f"Policy rule '{finding.category}' assigns severity {rule.get('severity', finding.severity)}"
            + (
                " with thresholds "
                + ", ".join(f"{k.replace('_', ' ')} = {v}" for k, v in thresholds.items())
                if thresholds else ""
            )
            + (f", anchored to {', '.join(rule.get('standards', []))}" if rule.get("standards") else "")
            + "."
        ),
    })
    steps.append({"kind": "reasoning", "title": "Why this follows", "text": finding.rationale})
    steps.append({
        "kind": "verdict",
        "title": f"Verdict: {finding.verdict} · {finding.severity}",
        "text": (
            f"Decided by {finding.detection_method} rule with confidence "
            f"{round(finding.confidence * 100)}%. "
            + (
                "UNKNOWN means the capture cannot support a conclusion either way."
                if finding.verdict == "UNKNOWN" else
                "The rule fired on observed facts; no model was involved in the verdict."
            )
        ),
    })

    # --- Confidence -----------------------------------------------------------
    confidence_factors = [
        {"factor": "Rule base confidence", "value": rule.get("confidence")},
    ]
    evidence = finding.evidence or {}
    if "baseline_scope" in evidence:
        confidence_factors.append({
            "factor": "Baseline scope",
            "value": evidence["baseline_scope"],
            "note": {
                "server_port": "Same server:port behaved normally elsewhere — strongest",
                "host": "Same host, different port — suggestive",
                "none": "No clean baseline in this capture — weakest",
            }.get(evidence["baseline_scope"]),
        })

    # --- Limits of the evidence -----------------------------------------------
    limits = []
    if capture.snaplen_truncated:
        limits.append("Packets were truncated at capture time (snaplen); payload analysis may be partial.")
    if session is not None:
        if session.has_gaps:
            limits.append("The reassembled stream has missing bytes.")
        if not session.session_complete:
            limits.append("The session's termination was not observed.")
        if session.tls_version and not session.cert_observable:
            limits.append(
                session.cert_unobservable_reason
                or "The server certificate was not observable in this capture."
            )
    if finding.session_ref is None:
        limits.append("Capture-level finding: it describes the observed environment, not one session.")

    # --- AI context (never a verdict) ------------------------------------------
    ml_context = None
    if session is not None and (session.anomaly_score is not None or session.baseline_deviations):
        ml_context = {
            "anomaly_score": session.anomaly_score,
            "is_anomalous": session.is_anomalous,
            "attribution": session.anomaly_attribution or [],
            "baseline_deviation_score": session.baseline_deviation_score,
            "baseline_deviations": session.baseline_deviations or [],
            "role": (
                "Context only. The Isolation Forest score and the per-server baseline "
                "deviations corroborate or question the finding; they never create or "
                "change a verdict."
            ),
        }

    # --- Posture impact --------------------------------------------------------
    impact = []
    ceiling = _SEVERITY_CEILING.get(finding.severity)
    for dim, categories in _DIMENSION_CATEGORIES.items():
        if finding.category in categories and ceiling is not None:
            impact.append({
                "dimension": _DIMENSION_LABELS.get(dim, dim),
                "ceiling": ceiling,
                "text": (
                    f"Caps {_DIMENSION_LABELS.get(dim, dim)} at {ceiling}/100 — posture "
                    "reflects the worst observed state, not the average."
                ),
            })

    return {
        "finding": {
            "ref": finding.ref,
            "title": finding.title,
            "category": finding.category,
            "severity": finding.severity,
            "verdict": finding.verdict,
            "confidence": finding.confidence,
            "detection_method": finding.detection_method,
            "description": finding.description,
            "recommendation": finding.recommendation,
            "standard_refs": finding.standard_refs or [],
            "session_ref": finding.session_ref,
            "affected_sessions": finding.affected_sessions,
        },
        "chain": steps,
        "observations": observations,
        "facts": _facts(evidence),
        "confidence_factors": confidence_factors,
        "limits": limits,
        "ml_context": ml_context,
        "posture_impact": impact,
        "blast_radius": blast_radius,
        "verification": {
            "wireshark_filter": finding.wireshark_filter,
            "evidence_frames": finding.evidence_frames or [],
            "pcap_url": f"/api/captures/{capture.id}/findings/{finding.ref}/pcap",
            "capture_sha256": capture.sha256,
            "capture_ref": capture.ref,
            "how": (
                "Download the evidence slice (its SHA-256 and the parent capture's are "
                "returned in the response headers), open it in Wireshark and apply the "
                "filter. Every frame cited above is inside it."
            ),
        },
    }
