"""Per-finding and per-session PCAP extraction.

The point of a slice: an analyst (or a judge) downloads the exact frames that
prove a finding, opens them in Wireshark, and confirms the claim independently
in seconds. A finding nobody can check is an assertion.

Two deliberate choices:

  * The slice is cut with **the same display filter shown in the UI**. If the
    filter and the slice could disagree, the "verify this yourself" promise
    would be hollow — so they are the same string, used once.
  * The slice records its own sha256 *and* the parent capture's, so the chain
    of custody survives the export. A slice with no link back to the evidence
    it came from is not evidence.
"""

from __future__ import annotations

import hashlib
import logging
import re
from dataclasses import dataclass
from pathlib import Path

from app.engines import ToolError, run_tool

logger = logging.getLogger(__name__)

# Display filters are generated by us, never by a user. This check exists so
# that stays true: if a filter ever picks up user-controlled text, the slicer
# refuses rather than passing it to a dissector.
_SAFE_FILTER = re.compile(r"^[A-Za-z0-9_.:\s=<>!&|()\[\]{},\-\"']+$")


class SliceError(RuntimeError):
    pass


@dataclass(frozen=True)
class PcapSlice:
    path: Path
    sha256: str
    size_bytes: int
    frame_count: int
    display_filter: str
    parent_sha256: str

    def manifest(self) -> dict:
        """Chain-of-custody record that travels with the exported file."""
        return {
            "filename": self.path.name,
            "sha256": self.sha256,
            "size_bytes": self.size_bytes,
            "frame_count": self.frame_count,
            "display_filter": self.display_filter,
            "extracted_from_sha256": self.parent_sha256,
        }


def _count_frames(path: Path) -> int:
    try:
        result = run_tool(["capinfos", "-M", "-c", str(path)], check=False)
    except ToolError:
        return 0
    for line in result.stdout.splitlines():
        if line.lower().startswith("number of packets"):
            try:
                return int(line.split(":", 1)[1].strip().split()[0])
            except (ValueError, IndexError):
                return 0
    return 0


def extract(
    source: Path,
    display_filter: str,
    destination: Path,
    parent_sha256: str,
    *,
    force: bool = False,
) -> PcapSlice:
    """Write the frames matching `display_filter` to `destination`."""
    if not display_filter or not _SAFE_FILTER.match(display_filter):
        raise SliceError("Refusing to slice with an unrecognised display filter.")

    destination.parent.mkdir(parents=True, exist_ok=True)

    # Slices are deterministic for a given capture and filter, so a cached one
    # is always valid. Re-running tshark per download would be pure waste.
    if destination.exists() and not force:
        data = destination.read_bytes()
        return PcapSlice(
            path=destination,
            sha256=hashlib.sha256(data).hexdigest(),
            size_bytes=len(data),
            frame_count=_count_frames(destination),
            display_filter=display_filter,
            parent_sha256=parent_sha256,
        )

    argv = [
        "tshark",
        "-r", str(source),
        "-n",
        "-Y", display_filter,
        "-w", str(destination),
        # pcapng preserves the original frame timestamps and link type, so the
        # slice opens exactly as the parent capture did.
        "-F", "pcapng",
    ]
    result = run_tool(argv, check=False)
    if not destination.exists():
        raise SliceError(
            f"tshark produced no output for filter {display_filter!r}: "
            f"{result.stderr.strip()[:200]}"
        )

    data = destination.read_bytes()
    frames = _count_frames(destination)
    if frames == 0:
        logger.warning("slice for %r matched no frames", display_filter)

    return PcapSlice(
        path=destination,
        sha256=hashlib.sha256(data).hexdigest(),
        size_bytes=len(data),
        frame_count=frames,
        display_filter=display_filter,
        parent_sha256=parent_sha256,
    )


def slice_path(capture_dir: Path, kind: str, ref: str) -> Path:
    """Where a slice is cached. `ref` is ours (SMTP-0001 / F-0001), never input."""
    safe = re.sub(r"[^A-Za-z0-9_-]", "_", ref)
    return capture_dir / "artifacts" / f"{kind}-{safe}.pcapng"
