"""Remediation playbooks: what to change, in which file, for which software.

Each fix is data, not prose generated on the fly:

  * which finding categories it resolves (so the simulator knows what to apply),
  * who owns it and how much effort it is (so the planner can order the work),
  * the exact configuration change per server product, as a diff,
  * the command that proves the change took effect, and
  * the standard that makes it the right change.

Templates are filled with the observed hostname, port and domain, so an
administrator can paste them. Nothing here is generated by a language model;
every line was written against the product's documented configuration syntax.
"""

from __future__ import annotations

from dataclasses import dataclass, field

EFFORT_LABEL = {1: "Low — configuration change", 2: "Medium — change + coordination", 3: "High — upgrade or migration"}


@dataclass
class Snippet:
    file: str
    lines: list[tuple[str, str]]          # ("+", "line") | ("-", "line") | (" ", "context")
    apply: list[str] = field(default_factory=list)
    note: str | None = None
    lang: str = "ini"


@dataclass
class Fix:
    id: str
    title: str
    summary: str
    resolves: set[str]
    owner: str
    effort: int
    group: str
    standards: list[str]
    rationale: str
    snippets: dict[str, list[Snippet]]
    verify: list[str]
    expected_outcome: str
    caution: str | None = None
    simulated: bool = True


def _s(file: str, *lines: str, apply: list[str] | None = None, note: str | None = None,
       lang: str = "ini") -> Snippet:
    parsed = []
    for line in lines:
        op, text = (line[0], line[2:]) if line[:2] in ("+ ", "- ", "  ") else (" ", line)
        parsed.append((op, text))
    return Snippet(file=file, lines=parsed, apply=apply or [], note=note, lang=lang)


FIXES: dict[str, Fix] = {}


def _fix(fix: Fix) -> None:
    FIXES[fix.id] = fix


# --------------------------------------------------------------------------- #
_fix(Fix(
    id="enforce_tls",
    title="Offer and require TLS before authentication and mail transfer",
    summary=(
        "Advertise STARTTLS/STLS, refuse AUTH and mailbox login until TLS is up, and require "
        "TLS on submission and mailbox ports."
    ),
    resolves={
        "cleartext_credential_exposure", "starttls_advertised_not_used",
        "starttls_not_advertised", "cleartext_mail_transaction", "starttls_downgrade_fallback",
    },
    owner="Mail server administrator",
    effort=1,
    group="transport",
    standards=["RFC 8314 §3", "RFC 3207", "RFC 4954 §4", "NIST SP 800-177r1 §4.5"],
    rationale=(
        "Credentials and message content crossed the network in cleartext. Requiring TLS on "
        "submission (587/465) and mailbox access (143/993, 110/995) removes the cleartext path "
        "entirely; refusing AUTH before TLS stops credential exposure even for misconfigured clients."
    ),
    snippets={
        "postfix": [
            _s("/etc/postfix/main.cf",
               "+ smtpd_tls_cert_file = /etc/ssl/mail/fullchain.pem",
               "+ smtpd_tls_key_file  = /etc/ssl/mail/privkey.pem",
               "- smtpd_tls_security_level = none",
               "+ smtpd_tls_security_level = may",
               "+ smtpd_tls_auth_only = yes",
               apply=["postfix check", "systemctl reload postfix"]),
            _s("/etc/postfix/master.cf",
               "  submission inet n - y - - smtpd",
               "+   -o smtpd_tls_security_level=encrypt",
               "+   -o smtpd_sasl_auth_enable=yes",
               note="Port 25 stays 'may' — RFC 3207 forbids a public MX from requiring TLS; protect it with MTA-STS instead."),
        ],
        "exim": [
            _s("/etc/exim4/exim4.conf.template",
               "+ tls_advertise_hosts = *",
               "+ tls_certificate = /etc/ssl/mail/fullchain.pem",
               "+ tls_privatekey  = /etc/ssl/mail/privkey.pem",
               "+ auth_advertise_hosts = ${if eq{$tls_in_cipher}{}{}{*}}",
               apply=["update-exim4.conf", "systemctl reload exim4"]),
            _s("/etc/exim4/conf.d/acl/30_exim4-config_check_rcpt",
               "+ deny  condition = ${if eq{$received_port}{587}}",
               "+       !encrypted = *",
               "+       message   = 530 5.7.0 Must issue a STARTTLS command first"),
        ],
        "sendmail": [
            _s("/etc/mail/sendmail.mc",
               "+ define(`confSERVER_CERT', `/etc/ssl/mail/fullchain.pem')dnl",
               "+ define(`confSERVER_KEY', `/etc/ssl/mail/privkey.pem')dnl",
               "+ define(`confAUTH_OPTIONS', `A p y')dnl",
               apply=["m4 /etc/mail/sendmail.mc > /etc/mail/sendmail.cf", "systemctl restart sendmail"],
               note="AUTH option 'p' disallows plaintext mechanisms without TLS."),
        ],
        "exchange": [
            _s("Exchange Management Shell",
               '+ Set-ReceiveConnector "$env:COMPUTERNAME\\Client Frontend $env:COMPUTERNAME" -RequireTLS $true -AuthMechanism Tls,Integrated,BasicAuth,BasicAuthRequireTLS',
               "+ Set-ImapSettings -LoginType SecureLogin",
               "+ Set-PopSettings  -LoginType SecureLogin",
               apply=["Restart-Service MSExchangeFrontEndTransport, MSExchangeIMAP4, MSExchangePOP3"],
               lang="powershell"),
        ],
        "dovecot": [
            _s("/etc/dovecot/conf.d/10-ssl.conf",
               "- ssl = no",
               "+ ssl = required",
               "+ ssl_cert = </etc/ssl/mail/fullchain.pem",
               "+ ssl_key  = </etc/ssl/mail/privkey.pem"),
            _s("/etc/dovecot/conf.d/10-auth.conf",
               "- disable_plaintext_auth = no",
               "+ disable_plaintext_auth = yes",
               apply=["doveconf -n >/dev/null", "systemctl reload dovecot"],
               note="Dovecot 2.4 renames this to auth_allow_cleartext = no."),
        ],
        "generic_smtp": [
            _s("MTA TLS configuration",
               "+ advertise STARTTLS on every listener",
               "+ refuse AUTH until TLS is established",
               "+ require TLS on submission (587) and use implicit TLS on 465",
               lang="text"),
        ],
        "generic_mailbox": [
            _s("IMAP/POP3 server TLS configuration",
               "+ advertise STARTTLS (IMAP) / STLS (POP3)",
               "+ reject LOGIN / USER+PASS until TLS is established",
               "+ prefer implicit TLS on 993 / 995",
               lang="text"),
        ],
    },
    verify=[
        "openssl s_client -starttls {starttls} -connect {host}:{port} -brief </dev/null",
        "swaks --server {host}:{port} --auth LOGIN --auth-user probe --auth-password x --quit-after AUTH   # must answer 530 5.7.0 without TLS",
    ],
    expected_outcome="Sessions that previously stayed in cleartext negotiate TLS; no credential or message is visible in a new capture.",
))

_fix(Fix(
    id="deploy_mta_sts_dane",
    title="Publish MTA-STS (enforce), DANE/TLSA and TLS-RPT",
    summary=(
        "Tell sending servers that this domain requires TLS with a valid certificate, so an "
        "on-path attacker can no longer strip STARTTLS and force cleartext delivery."
    ),
    resolves={
        "starttls_stripping", "mta_sts_policy_violation", "mta_sts_not_published",
        "dane_not_deployed", "tlsrpt_not_configured",
    },
    owner="DNS and mail administrators",
    effort=2,
    group="dns",
    standards=["RFC 8461 (MTA-STS)", "RFC 7672 (DANE for SMTP)", "RFC 8460 (TLS-RPT)"],
    rationale=(
        "STARTTLS is opportunistic: a sender that never sees the capability falls back to "
        "cleartext. MTA-STS in enforce mode and DANE make TLS mandatory for compliant senders, "
        "turning a silent downgrade into a delivery deferral that TLS-RPT reports to you."
    ),
    snippets={
        "_all": [
            _s("DNS zone {domain}",
               '+ _mta-sts.{domain}.   3600 IN TXT  "v=STSv1; id=20260930T000000"',
               '+ _smtp._tls.{domain}. 3600 IN TXT  "v=TLSRPTv1; rua=mailto:tls-reports@{domain}"',
               "+ _25._tcp.{host}.     3600 IN TLSA 3 1 1 <sha256-of-server-SPKI>",
               lang="dns",
               note="TLSA needs a DNSSEC-signed zone. Compute the hash with the command below."),
            _s("https://mta-sts.{domain}/.well-known/mta-sts.txt",
               "+ version: STSv1",
               "+ mode: enforce",
               "+ mx: {host}",
               "+ max_age: 604800",
               lang="text",
               note="Start with mode: testing for one week and read the TLS-RPT reports before enforcing."),
            _s("compute TLSA hash",
               "+ openssl x509 -in fullchain.pem -noout -pubkey | openssl pkey -pubin -outform DER | openssl dgst -sha256",
               lang="shell"),
        ],
        "postfix": [
            _s("/etc/postfix/main.cf (outbound, for your own relays)",
               "+ smtp_dns_support_level = dnssec",
               "+ smtp_tls_security_level = dane",
               apply=["systemctl reload postfix"]),
        ],
    },
    verify=[
        "dig +short TXT _mta-sts.{domain}",
        "curl -s https://mta-sts.{domain}/.well-known/mta-sts.txt",
        "dig +short TLSA _25._tcp.{host}",
    ],
    expected_outcome="Compliant senders refuse cleartext delivery to this domain; stripped sessions are deferred and reported instead of delivered unencrypted.",
))

_fix(Fix(
    id="disable_legacy_tls",
    title="Disable TLS 1.0 and TLS 1.1 (minimum TLS 1.2)",
    summary="Remove protocol versions deprecated by RFC 8996 from every listener.",
    resolves={"deprecated_tls_version"},
    owner="Mail server administrator",
    effort=1,
    group="protocol",
    standards=["RFC 8996", "NIST SP 800-52r2 §3.1"],
    rationale=(
        "TLS 1.0 and 1.1 rely on SHA-1/MD5 in the handshake and lack modern AEAD suites. "
        "Every major client supports TLS 1.2; the only clients broken by this change are ones "
        "that should not be trusted with mail."
    ),
    snippets={
        "postfix": [_s("/etc/postfix/main.cf",
                       "- smtpd_tls_protocols = !SSLv2, !SSLv3",
                       "+ smtpd_tls_protocols = >=TLSv1.2",
                       "+ smtpd_tls_mandatory_protocols = >=TLSv1.2",
                       "+ smtp_tls_protocols = >=TLSv1.2",
                       "+ smtp_tls_mandatory_protocols = >=TLSv1.2",
                       apply=["postfix check", "systemctl reload postfix"],
                       note="'>=TLSv1.2' syntax needs Postfix 3.6+. Older: !SSLv2, !SSLv3, !TLSv1, !TLSv1.1")],
        "exim": [_s("/etc/exim4/exim4.conf.template",
                    "+ openssl_options = +no_sslv2 +no_sslv3 +no_tlsv1 +no_tlsv1_1",
                    apply=["update-exim4.conf", "systemctl reload exim4"])],
        "sendmail": [_s("/etc/mail/sendmail.mc",
                        "+ LOCAL_CONFIG",
                        "+ O ServerSSLOptions=+SSL_OP_NO_SSLv2 +SSL_OP_NO_SSLv3 +SSL_OP_NO_TLSv1 +SSL_OP_NO_TLSv1_1",
                        apply=["m4 /etc/mail/sendmail.mc > /etc/mail/sendmail.cf", "systemctl restart sendmail"])],
        "exchange": [_s("Windows registry (SCHANNEL) — PowerShell",
                        "+ foreach ($v in 'TLS 1.0','TLS 1.1') { foreach ($r in 'Server','Client') {",
                        "+   $k = \"HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\$v\\$r\"",
                        "+   New-Item $k -Force | Out-Null",
                        "+   New-ItemProperty $k -Name Enabled -Value 0 -PropertyType DWord -Force",
                        "+   New-ItemProperty $k -Name DisabledByDefault -Value 1 -PropertyType DWord -Force } }",
                        apply=["Restart-Computer   # SCHANNEL changes need a reboot"],
                        lang="powershell")],
        "dovecot": [_s("/etc/dovecot/conf.d/10-ssl.conf",
                       "+ ssl_min_protocol = TLSv1.2",
                       apply=["systemctl reload dovecot"])],
        "generic_smtp": [_s("TLS library configuration", "+ MinProtocol = TLSv1.2", lang="text")],
        "generic_mailbox": [_s("TLS library configuration", "+ MinProtocol = TLSv1.2", lang="text")],
    },
    verify=[
        "openssl s_client -starttls {starttls} -connect {host}:{port} -tls1_1 </dev/null   # must fail",
        "openssl s_client -starttls {starttls} -connect {host}:{port} -tls1_2 -brief </dev/null   # must succeed",
    ],
    expected_outcome="Handshakes negotiate TLS 1.2 or 1.3; clients limited to TLS 1.0/1.1 fail to connect.",
))

_fix(Fix(
    id="modern_ciphers",
    title="Allow only ECDHE key exchange with AEAD ciphers",
    summary="Remove static-RSA key transport, CBC, 3DES and RC4; keep ECDHE with AES-GCM or ChaCha20-Poly1305.",
    resolves={"weak_cipher_suite", "no_forward_secrecy"},
    owner="Mail server administrator",
    effort=1,
    group="cipher",
    standards=["NIST SP 800-52r2 §3.3.1", "Mozilla Server Side TLS (Intermediate)", "RFC 7465", "RFC 9325"],
    rationale=(
        "Static RSA key exchange means one leaked server key decrypts every recorded session "
        "(harvest-now, decrypt-later). CBC suites have a long history of padding-oracle attacks; "
        "RC4 and 3DES are prohibited. ECDHE+AEAD gives forward secrecy and authenticated encryption."
    ),
    snippets={
        "postfix": [_s("/etc/postfix/main.cf",
                       "+ smtpd_tls_mandatory_ciphers = high",
                       "+ smtpd_tls_ciphers = high",
                       "+ tls_high_cipherlist = ECDHE+AESGCM:ECDHE+CHACHA20",
                       "+ smtpd_tls_exclude_ciphers = aNULL, eNULL, kRSA, RC4, 3DES, MD5, SHA1",
                       "+ tls_preempt_cipherlist = yes",
                       apply=["systemctl reload postfix"])],
        "exim": [_s("/etc/exim4/exim4.conf.template",
                    "+ tls_require_ciphers = ECDHE+AESGCM:ECDHE+CHACHA20:!aNULL:!kRSA",
                    apply=["update-exim4.conf", "systemctl reload exim4"])],
        "sendmail": [_s("/etc/mail/sendmail.mc",
                        "+ LOCAL_CONFIG",
                        "+ O CipherList=ECDHE+AESGCM:ECDHE+CHACHA20:!aNULL:!kRSA",
                        apply=["m4 /etc/mail/sendmail.mc > /etc/mail/sendmail.cf", "systemctl restart sendmail"])],
        "exchange": [_s("PowerShell (Windows TLS cipher suite order)",
                        "+ 'TLS_RSA_WITH_AES_128_CBC_SHA','TLS_RSA_WITH_AES_256_CBC_SHA','TLS_RSA_WITH_3DES_EDE_CBC_SHA' |",
                        "+   ForEach-Object { Disable-TlsCipherSuite -Name $_ }",
                        "+ Enable-TlsCipherSuite -Name TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 -Position 0",
                        "+ Enable-TlsCipherSuite -Name TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 -Position 1",
                        apply=["Restart-Computer"], lang="powershell")],
        "dovecot": [_s("/etc/dovecot/conf.d/10-ssl.conf",
                       "+ ssl_cipher_list = ECDHE+AESGCM:ECDHE+CHACHA20:!aNULL:!kRSA",
                       "+ ssl_prefer_server_ciphers = yes",
                       apply=["systemctl reload dovecot"])],
        "generic_smtp": [_s("TLS library configuration", "+ CipherString = ECDHE+AESGCM:ECDHE+CHACHA20:!aNULL:!kRSA", lang="text")],
        "generic_mailbox": [_s("TLS library configuration", "+ CipherString = ECDHE+AESGCM:ECDHE+CHACHA20:!aNULL:!kRSA", lang="text")],
    },
    verify=[
        "nmap --script ssl-enum-ciphers -p {port} {host}   # every suite should grade A",
        "openssl s_client -starttls {starttls} -connect {host}:{port} -cipher AES128-SHA -tls1_2 </dev/null   # must fail",
    ],
    expected_outcome="Every TLS 1.2 handshake uses ECDHE with an AEAD cipher; sessions gain forward secrecy.",
))

_fix(Fix(
    id="renew_certificate",
    title="Re-issue the server certificate (valid, ≥2048-bit / P-256, SHA-256, correct names)",
    summary="Replace the certificate with one from a trusted CA that covers every mail hostname, and deploy the full chain.",
    resolves={
        "certificate_expired", "certificate_not_yet_valid", "certificate_expiring_soon",
        "certificate_hostname_mismatch", "certificate_weak_key", "certificate_weak_signature",
        "certificate_self_signed", "certificate_chain_incomplete", "certificate_chain_invalid",
    },
    owner="Mail server administrator / PKI team",
    effort=2,
    group="certificate",
    standards=["CA/Browser Forum Baseline Requirements", "RFC 5280", "NIST SP 800-57 Part 1 Rev 5"],
    rationale=(
        "Clients that validate certificates will refuse this server, and clients that do not are "
        "open to impersonation. A short-lived certificate from an automated CA removes expiry as "
        "a failure mode altogether."
    ),
    snippets={
        "_all": [_s("shell (ACME / certbot)",
                    "+ certbot certonly --standalone -d {host} --key-type ecdsa --elliptic-curve secp256r1 \\",
                    "+     --deploy-hook 'systemctl reload postfix dovecot'",
                    lang="shell",
                    note="Internal CA instead? Issue RSA-3072 or P-256, SHA-256, with SAN={host}, and ship leaf + intermediates.")],
        "postfix": [_s("/etc/postfix/main.cf",
                       "- smtpd_tls_cert_file = /etc/ssl/mail/old.pem",
                       "+ smtpd_tls_chain_files = /etc/letsencrypt/live/{host}/privkey.pem,",
                       "+                         /etc/letsencrypt/live/{host}/fullchain.pem",
                       apply=["systemctl reload postfix"])],
        "exim": [_s("/etc/exim4/exim4.conf.template",
                    "+ tls_certificate = /etc/letsencrypt/live/{host}/fullchain.pem",
                    "+ tls_privatekey  = /etc/letsencrypt/live/{host}/privkey.pem",
                    apply=["systemctl reload exim4"])],
        "exchange": [_s("Exchange Management Shell",
                        '+ $req = New-ExchangeCertificate -GenerateRequest -SubjectName "CN={host}" -DomainName {host} -KeySize 3072 -PrivateKeyExportable $true',
                        "+ # submit $req to the CA, then:",
                        '+ Import-ExchangeCertificate -FileData ([IO.File]::ReadAllBytes("C:\\certs\\{host}.cer")) | Enable-ExchangeCertificate -Services SMTP,IMAP,POP',
                        lang="powershell")],
        "dovecot": [_s("/etc/dovecot/conf.d/10-ssl.conf",
                       "+ ssl_cert = </etc/letsencrypt/live/{host}/fullchain.pem",
                       "+ ssl_key  = </etc/letsencrypt/live/{host}/privkey.pem",
                       apply=["systemctl reload dovecot"])],
    },
    verify=[
        "openssl s_client -starttls {starttls} -connect {host}:{port} -servername {host} -showcerts </dev/null | openssl x509 -noout -dates -subject -ext subjectAltName",
        "openssl s_client -starttls {starttls} -connect {host}:{port} -verify_return_error </dev/null   # Verify return code: 0 (ok)",
    ],
    expected_outcome="The presented leaf is within its validity window, uses a strong key and SHA-256, covers the hostname and chains to a trusted root.",
))

_fix(Fix(
    id="fix_certificate_chain",
    title="Serve the complete certificate chain",
    summary="Configure the server to send the leaf together with its intermediate CA certificate(s).",
    resolves={"certificate_chain_incomplete", "certificate_chain_invalid"},
    owner="Mail server administrator",
    effort=1,
    group="certificate",
    standards=["RFC 5246 §7.4.2", "RFC 8446 §4.4.2", "RFC 5280 §6"],
    rationale="Clients without the intermediate cached cannot build a path to the root and fail validation.",
    snippets={
        "postfix": [_s("/etc/postfix/main.cf",
                       "- smtpd_tls_cert_file = /etc/ssl/mail/cert.pem",
                       "+ smtpd_tls_chain_files = /etc/ssl/mail/privkey.pem, /etc/ssl/mail/fullchain.pem",
                       apply=["systemctl reload postfix"])],
        "dovecot": [_s("/etc/dovecot/conf.d/10-ssl.conf",
                       "- ssl_cert = </etc/ssl/mail/cert.pem",
                       "+ ssl_cert = </etc/ssl/mail/fullchain.pem",
                       apply=["systemctl reload dovecot"])],
        "_all": [_s("shell", "+ cat cert.pem intermediate.pem > fullchain.pem", lang="shell")],
    },
    verify=["openssl s_client -starttls {starttls} -connect {host}:{port} -showcerts </dev/null | grep -c 'BEGIN CERTIFICATE'   # expect ≥ 2"],
    expected_outcome="Two or more certificates are presented and every link verifies.",
))

_fix(Fix(
    id="enable_hybrid_pqc",
    title="Enable hybrid post-quantum key exchange (X25519MLKEM768)",
    summary="Prefer the hybrid ML-KEM group on TLS 1.3 so clients that already offer it get quantum-resistant key agreement.",
    resolves={"pqc_server_not_ready"},
    owner="Mail server administrator",
    effort=3,
    group="pqc",
    standards=["FIPS 203 (ML-KEM)", "draft-ietf-tls-ecdhe-mlkem", "NSA CNSA 2.0"],
    rationale=(
        "Mail is long-lived: traffic recorded today can be decrypted once a cryptographically "
        "relevant quantum computer exists. Hybrid ML-KEM protects key agreement now while keeping "
        "classical X25519 security."
    ),
    snippets={
        "postfix": [_s("/etc/postfix/main.cf",
                       "+ tls_eecdh_auto_curves = X25519MLKEM768 X25519 prime256v1 secp384r1",
                       apply=["systemctl reload postfix"],
                       note="Requires OpenSSL 3.5+ linked into Postfix.")],
        "dovecot": [_s("/etc/dovecot/conf.d/10-ssl.conf",
                       "+ ssl_curve_list = X25519MLKEM768:X25519:prime256v1",
                       apply=["systemctl reload dovecot"],
                       note="Requires OpenSSL 3.5+.")],
        "_all": [_s("/etc/ssl/openssl.cnf (system default)",
                    "+ [system_default_sect]",
                    "+ Groups = X25519MLKEM768:X25519:prime256v1",
                    note="Upgrade to OpenSSL 3.5+ first; earlier versions reject the group name.")],
    },
    verify=["openssl s_client -starttls {starttls} -connect {host}:{port} -groups X25519MLKEM768 </dev/null 2>&1 | grep -i 'group'"],
    expected_outcome="TLS 1.3 sessions from PQC-capable clients negotiate X25519MLKEM768.",
    caution="Only sessions whose client already offers a hybrid group can change; the rest need client upgrades.",
))

_fix(Fix(
    id="publish_dmarc",
    title="Publish an enforcing DMARC policy",
    summary="Publish DMARC with p=quarantine (then reject) and aggregate reporting.",
    resolves={"dmarc_not_published", "dmarc_policy_none"},
    owner="DNS administrator",
    effort=1,
    group="dns",
    standards=["RFC 7489", "NIST SP 800-177r1 §4.6"],
    rationale="Without an enforcing DMARC policy, receivers accept mail that spoofs this domain.",
    snippets={"_all": [_s("DNS zone {domain}",
                          '+ _dmarc.{domain}. 3600 IN TXT "v=DMARC1; p=quarantine; rua=mailto:dmarc@{domain}; adkim=s; aspf=s"',
                          lang="dns")]},
    verify=["dig +short TXT _dmarc.{domain}"],
    expected_outcome="Receivers quarantine mail failing SPF/DKIM alignment for this domain.",
))

_fix(Fix(
    id="standard_ports",
    title="Move the mail service to its registered port",
    summary="Serve SMTP on 25/587/465 and IMAP/POP3 on 143/993/110/995 so TLS policy and monitoring apply.",
    resolves={"protocol_port_mismatch"},
    owner="Network / mail administrator",
    effort=2,
    group="exposure",
    standards=["RFC 6409", "RFC 8314"],
    rationale="Services on unexpected ports usually escape the TLS policy, firewall rules and monitoring applied to the standard ones.",
    snippets={
        "postfix": [_s("/etc/postfix/master.cf",
                       "- {port}      inet  n  -  y  -  -  smtpd",
                       "+ submission inet  n  -  y  -  -  smtpd",
                       "+ submissions inet n  -  y  -  -  smtpd",
                       "+   -o smtpd_tls_wrappermode=yes",
                       apply=["systemctl reload postfix"])],
        "_all": [_s("listener configuration", "- listen on {port}", "+ listen on the registered port for the protocol", lang="text")],
    },
    verify=["ss -ltnp | grep -E ':(25|465|587|143|993|110|995)\\b'"],
    expected_outcome="No mail service answers on a non-registered port.",
))

# Evidence actions: they improve what the next capture can prove, not the posture.
EVIDENCE_ACTIONS = {
    "incomplete_evidence": "Re-capture with full snaplen and for the full session lifetime.",
    "certificate_not_observable": "TLS 1.3 encrypts the certificate. Capture with SSLKEYLOGFILE, or probe the server once with openssl s_client -showcerts.",
    "dns_correlation_incomplete": "Capture the DNS resolution (A/AAAA of the MX hosts) together with the SMTP sessions.",
}


def fix_for_category(category: str) -> list[Fix]:
    """Fixes that resolve a category, most targeted first."""
    return sorted((f for f in FIXES.values() if category in f.resolves), key=lambda f: (len(f.resolves), f.effort))


_STARTTLS_FLAG = {"SMTP": "smtp", "IMAP": "imap", "POP3": "pop3"}


def render(fix: Fix, server: dict | None) -> dict:
    """Fill a fix's templates for one server (software, host, port, domain)."""
    server = server or {}
    host = server.get("hostname") or "mail.example.org"
    domain = host.split(".", 1)[1] if host.count(".") >= 2 and not host[0].isdigit() else host
    port = server.get("port") or 25
    protocol = server.get("protocol") or "SMTP"
    values = {
        "host": host, "domain": domain, "port": port,
        "starttls": _STARTTLS_FLAG.get(protocol, "smtp"),
    }

    software = server.get("key") or ("generic_smtp" if protocol == "SMTP" else "generic_mailbox")
    chosen = fix.snippets.get(software)
    matched = chosen is not None
    if chosen is None:
        family = "generic_smtp" if protocol == "SMTP" else "generic_mailbox"
        chosen = fix.snippets.get(family, [])
    common = fix.snippets.get("_all", [])

    def fill(text: str) -> str:
        try:
            return text.format(**values)
        except (KeyError, IndexError, ValueError):
            return text

    def snippet(sn: Snippet) -> dict:
        return {
            "file": fill(sn.file),
            "lang": sn.lang,
            "lines": [{"op": op, "text": fill(t) if "{" in t and "${" not in t else t} for op, t in sn.lines],
            "apply": [fill(a) for a in sn.apply],
            "note": fill(sn.note) if sn.note else None,
        }

    # Implicit-TLS ports have no STARTTLS step in verification commands.
    verify = [fill(v) for v in fix.verify]
    if port in (465, 993, 995):
        verify = [v.replace(f"-starttls {values['starttls']} ", "") for v in verify]

    return {
        "id": fix.id,
        "title": fix.title,
        "summary": fix.summary,
        "owner": fix.owner,
        "effort": fix.effort,
        "effort_label": EFFORT_LABEL[fix.effort],
        "group": fix.group,
        "standards": fix.standards,
        "rationale": fix.rationale,
        "resolves": sorted(fix.resolves),
        "software": {
            "key": software, "name": server.get("name"), "version": server.get("version"),
            "evidence": server.get("evidence"), "specific": matched,
        },
        "target": {"server": server.get("server"), "host": host, "port": port, "domain": domain},
        "snippets": [snippet(s) for s in chosen + common],
        "verify": verify + [
            "Re-capture the same traffic and upload it: the Drift view compares the new posture to this one.",
        ],
        "expected_outcome": fix.expected_outcome,
        "caution": fix.caution,
    }
